version: "3.4"
services:
  clamav:
    image: ghcr.io/t7tran/clamav:1.2.1
    read_only: true
    volumes:
      - clamav:/clamav:rw
      - tmp:/run/clamav:rw
      - tmp:/tmp:rw
  client:
    image: ghcr.io/t7tran/clamav:1.2.1
    read_only: true
    working_dir: /client
    depends_on:
      - clamav
    command:
      - client
    environment:
      - CLAMDSCAN_TCPADDR=clamav
    volumes:
      - ./client:/client:rw
      - tmp:/tmp:rw
volumes:
  clamav:
    labels:
      - "keep=true"
      - "app=clamav"
  tmp:
    labels:
      - "app=clamav"
